### ISSUE TITLE
Kernel freeze 

### ISSUE THREAD

**Issue by Maxes27** [Official-Ayrton990/android_kernel_xiaomi_sm8150#3] opened 2020-07-31 10:29 UTC
Quantic kernel r24 on miui 12 30/07/2020 version freezes when launching any app after booting up, won't unfreeze until rebooting, and process repeats after rebooting and launching and app again. Flashed the kernel post flashing magisk. Had to revert back to r21.

**Comment by Official-Ayrton990** [comment] 2020-07-31 17:07
The issue is present only on r24. you can use r23 without a problem, it will be fixed soon. 
Sorry for inconvenience

Regards, Ayrton.

**Comment by Official-Ayrton990** [comment] 2020-08-03 19:00
Issue it's solved for both: Cepheus and Raphael

Please download from releases

Regards, Ayrton.

**Closed as completed by Official-Ayrton990** 2020-08-03 19:00 UTC
